



export const searchKeywords: string[] = [
    "Bombing",
    "Explosion",
    "Explosives",
    "Pipe bomb",
    "General Electric",
    "Strikers",
    "Educational Institution",
    "Government",
    "Jurists Ball",
    "Black Nationalists",
    "Commune 1",
    "North America",
    "United States",
    "East Germany",
    "GDR (German Democratic Republic)",
    "Berlin",
    "New York City",
    "Rio Grande",
    "Seattle",
    "Attack",
    "Terrorism",
    "Violent",
    "Target",
    "Perpetrator",
    "Attack Type",
    "Terrorist Group",
    "Victims",
    "Wounded",
    "Bomb",
    "Bomb Threat",
    "Civil unrest",
    "Political violence",
    "Radical groups",
    "Military action",
    "Political targets",
    "Explosive devices",
    "Urban warfare",
    "Public safety",
    "Emergency response",
    "National security",
    "Casualties",
    "Attack Strategy",
    "Attack Plan",
    "Anti-government",
    "Protest",
    "Protestors",
    "Bomb maker",
    "Criminal acts",
    "Political clash",
    "Freedom Fighters",
    "Historical attacks",
    "1970",
    "1970s",
    "Political violence history",
    "Military explosives",
    "Public spaces",
    "Strategic target",
    "International attack",
    "Violent demonstration",
    "Radical movements",
    "Social unrest",
    "Resistance movement",
    "Terrorist threat",
    "Attacks on civilians",
    "School bombing",
    "Pipe bomb attack",
    "Factory explosion",
    "Mass casualty event",
    "Anti-authority",
    "Civilian casualties",
    "Guerrilla warfare",
    "Assailants",
    "Military base attack",
    "Political assassination",
    "Infiltration",
    "Protest march",
    "Political target",
    "Occupation",
    "Historical violence",
    "Global terrorism",
    "Geopolitical conflict",
    "Protest violence",
    "Armed attack",
    "Explosive attack",
    "International terrorism",
    "Detonated bomb",
    "Strategic location",
    "Demolition",
    "Resistance group",
    "Urban terrorism",
    "International attack",
    "Bomb damage",
    "Damage control",
    "Explosive ordinance",
    "Political disruption",
    "Domestic attack",
    "Global unrest",
    "Violent protests",
    "Anti-establishment",
    "Civil rights group"
  ];